### ISSUE TITLE
Javac plugins cannot be found

### ISSUE THREAD

**Issue by Trigary** [google/compile-testing#215] opened 2021-01-05 22:33 UTC
I am trying to use this library to unit test a `javac` plugin.

The plugin works fine when compilation is done through `javac` directly:
```sh
javac src/test/resources/HelloWorld.java -Xplugin:SamplePlugin -cp 'target/classes/'
```

But the following unit test fails:
```java
/**
 * Fails, while it shouldn't. The error message:
 * error: plug-in not found: SamplePlugin
 * No files were generated.
 *   at sample@1.0/sample.SampleTest.withPlugin(SampleTest.java:48)
 */
@Test
public void withPlugin() {
	Compilation compilation = Compiler.javac()
			.withOptions("-Xplugin:SamplePlugin")
			.withClasspath(List.of(new File("target/classes")))
			.compile(JavaFileObjects.forResource("HelloWorld.java"));
	CompilationSubject.assertThat(compilation).succeeded();
}
```

The classpath itself is correct, as demonstrated by these unit tests:
```java
/**
 * The compilation fails due to {@code sample.SampleClass} not being available.
 */
@Test
public void withoutClasspath() {
	Compilation compilation = Compiler.javac()
			.compile(JavaFileObjects.forResource("HelloWorld.java"));
	CompilationSubject.assertThat(compilation).failed();
}

/**
 * Compilation succeeds.
 */
@Test
public void withoutPlugin() {
	Compilation compilation = Compiler.javac()
			.withClasspath(List.of(new File("target/classes")))
			.compile(JavaFileObjects.forResource("HelloWorld.java"));
	CompilationSubject.assertThat(compilation).succeeded();
}
```

I have uploaded this minimalistic sample Maven project to help the confirmation and the reproduction of this issue: [Sample.zip](https://github.com/google/compile-testing/files/5772943/Sample.zip)

**Comment by elkkhan** [comment] 2024-01-06 23:54
adding the `-XDcompilePolicy` [flag](https://www.javadoc.io/doc/io.earcam.wrapped/jdk.compiler/latest/com/sun/tools/javac/main/JavaCompiler.CompilePolicy.html) (with any possible value - `simple` should be good enough) solves this.

``` java
@Test
public void withPlugin() {
	Compilation compilation = Compiler.javac()
			.withOptions("-XDcompilePolicy=simple -Xplugin:SamplePlugin")
			.withClasspath(List.of(new File("target/classes")))
			.compile(JavaFileObjects.forResource("HelloWorld.java"));
	CompilationSubject.assertThat(compilation).succeeded();
}

**Comment by elkkhan** [comment] 2024-01-07 01:08
I was running into a similar issue - your sample project helped me debug this and find the root cause.

Your plugin is being discovered by the `ServiceLoader` but it's being [ignored](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/ServiceLoader.java#L1228-L1231).

The reason for this is that your plugin resides in the `sample` module but your `module-info.java` file does not export the plugin. 
The `ServiceLoader` first tries to search for service providers in named modules - it doesn't find one in your case.
Then, it tries to search for service providers declared via config files, like you have done in your `META-INF/services` directory. Your plugin is found as a service provider at this step, but it's ignored because it's part of a named module.
From [ServiceLoader javadoc](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/util/ServiceLoader.html):

>In a provider-configuration file, any mention of a service provider that is deployed in a named module is ignored. This is to avoid duplicates that would otherwise arise when a named module has both a provides directive and a provider-configuration file that mention the same service provider.

You might want to add the following line to your `module-info.java` file and optionally remove the config in `META-INF/services`:

```java
provides com.sun.source.util.Plugin with sample.SamplePlugin;
```
BTW, 
At first I got a false positive from the test case in the project - you're asserting whether the compilation is success, but that does not ensure that the plugin was registered and invoked. I changed the plugin code to throw a custom exception on `init()` to make the test more reliable by changing the compilation success assert to `assertThrows(CustomException.class, () -> compile())`

**Comment by netdpb** [comment] 2024-01-08 15:38
Thanks, @elkkhan!

@Trigary, what if you use `withAnnotationProcessorPath()` to point to your plugin code instead of `withClasspath()`? (`SampleClass` has to be in the actual classpath.)

**Comment by Trigary** [comment] 2024-01-08 23:26
@netdpb When I originally opened the issue, the `withAnnotationProcessorPath()` method did not yet exist. I updated to the latest version of the library (`0.21.0`) and ran the following test, unfortunately, it also fails, just like the one in the original issue description.

```java
@Test
public void withPlugin() {
	Compilation compilation = Compiler.javac()
			.withOptions("-Xplugin:SamplePlugin")
			.withAnnotationProcessorPath(List.of(new File("target/classes")))
			.withClasspath(List.of(new File("target/classes")))
			.compile(JavaFileObjects.forResource("HelloWorld.java"));
	CompilationSubject.assertThat(compilation).succeeded();
}
```

---

Thank you @elkkhan for the explanation and the suggested modifications, your fix indeed works.

I don't know whether this issue should be closed or not. On the one hand, adding the `provides` line to `module-info.java`, as suggested by @elkkhan, should probably be done no matter whether we want to use `javac` directly or through this library. On the other hand, when using `javac` directly without the `provides` line, the compilation succeeds, and I believe this library should optimally mirror how `javac` works.

With that being said, I think this issue should be closed. Users can be expected to configure their modules correctly (to include the necessary `provides` statements).

**Comment by netdpb** [comment] 2024-01-09 18:07
It looks to me like this isn't an issue with Compile Testing per se, but a constraint on how JPMS works, so I'll close this issue. Please reopen if I've misunderstood.

**Closed by netdpb** 2024-01-09 18:07 UTC
Labels: type=defect, P3
